name: Android CI

on:
  push:
  pull_request:
    branches:
      - master
  release:
    types:
      - created
  # schedule:
  #   - cron: "0 7 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build with Gradle
      run: ./gradlew build --parallel --daemon
    - name: Run Unit Tests
      run: ./gradlew test
    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
    - name: Start logcat
      run: adb logcat -c && adb logcat *:V > logcat.txt &
    - name: Run Instrumented Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: x86_64
        # S24 is -skin 1080x2340 -dpi-device 425 -prop qemu.sf.lcd_density=425
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -skin 540x960 -dpi-device 240 -prop qemu.sf.lcd_density=240
        script: |
          ./gradlew connectedDebugAndroidTest createDebugCoverageReport
    - name: Show logcat
      if: always()
      run: cat logcat.txt | grep colorfilter
    - name: Upload Jacoco Reports
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-reports
        path: app/build/reports
    - name: Print Code Coverage Summary
      run: |
        COVERAGE_FILE=$(find app/build/reports -name "report.xml")
        if [ -f "$COVERAGE_FILE" ]; then
          COVERED=$(grep -oP 'covered="\K[0-9]+' $COVERAGE_FILE | awk '{s+=$1} END {print s}')
          MISSED=$(grep -oP 'missed="\K[0-9]+' $COVERAGE_FILE | awk '{s+=$1} END {print s}')
          TOTAL=$((COVERED + MISSED))
          PERCENTAGE=$(echo "scale=2; 100*$COVERED/$TOTAL" | bc)
          echo "$COVERED of $TOTAL statements covered ($PERCENTAGE%)"
        else
          echo "Jacoco coverage file not found."
        fi
    - name: Parse Coverage per Method
      run: |
        # Install xmlstarlet to parse XML
        sudo apt-get install -y xmlstarlet
        COVERAGE_FILE=$(find app/build/reports -name "report.xml")

        calculate_percentage() {
          local covered=$1
          local total=$2
          if [ $total -eq 0 ]; then
            echo "100.00"
          else
            echo "scale=2; 100* $covered / $total" | bc
          fi
        }

        echo "Method Coverage Details:"
        xmlstarlet sel -t -m "//method" \
          -v "concat(../../@name, '.', ../@name, '.', @name)" -o " " \
          -m "counter[@type='INSTRUCTION']" -v "@covered" -o " " -v "@missed" -n \
          "$COVERAGE_FILE" | while read -r method covered missed || [[ -n "$method" ]]; do
            if [ -n "$covered" ] && [ -n "$missed" ]; then
              total=$((covered + missed))
              percentage=$(calculate_percentage "$covered" "$total")
              echo "${percentage}|${method}: ${covered}/${total} (${percentage}%)"
            fi
        done | sort -n | cut -d'|' -f2-
    - name: Decode Keystore
      run: if [ -n "${{ secrets.KEYSTORE_BASE64 }}" ]; then echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks; fi
    - name: Build AAR
      env:
        SIGNING_STORE_FILE: ${{ github.workspace }}/keystore.jks
        SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew assembleRelease
    - name: Build AAB
      env:
        SIGNING_STORE_FILE: ${{ github.workspace }}/keystore.jks
        SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew bundleRelease
    # - name: Check
    #   run: find app/build -name "*.aab" && find app/build -name "*.apk" && find app/build -name "*.aar" && ls -lR app/build
    # - name: Upload AAR artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: color-filter-aar
    #     path: app/build/outputs/aar/*.aar
    - name: Upload Debug APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: color-filter-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: color-filter-apk
        path: app/build/outputs/apk/release/*.apk
    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: color-filter-aab
        path: app/build/outputs/bundle/release/*.aab
